name: CI Check

on:
  pull_request:
    branches: ["develop", "main"]
  push:
    branches: ["develop", "main"]

jobs:
  quality-check:
    name: ğŸ” Quality & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      # 1. ĞŸĞµÑ€ĞµĞ²Ñ–Ñ€ĞºĞ° ÑÑ‚Ğ¸Ğ»Ñ (Prettier)
      - name: ğŸ¨ Check Code Style
        run: npx prettier --check .

      # 2. ĞŸĞµÑ€ĞµĞ²Ñ–Ñ€ĞºĞ° Ğ¿Ğ¾Ğ¼Ğ¸Ğ»Ğ¾Ğº (ESLint)
      - name: ğŸš¨ Lint Code
        run: npm run lint

      # 3. Ğ¢ĞµÑÑ‚Ğ¸ (Ğ—Ğ°Ğ³Ğ»ÑƒÑˆĞºĞ°)
      - name: ğŸ§ª Run Tests
        run: echo "Skipping tests for now"

      # 4. Ğ‘Ñ–Ğ»Ğ´ Ğ¤Ñ€Ğ¾Ğ½Ñ‚ĞµĞ½Ğ´Ñƒ
      - name: ğŸ—ï¸ Build Frontend
        run: npm run build

      # 5. Ğ‘Ñ–Ğ»Ğ´ Ğ‘ĞµĞºĞµĞ½Ğ´Ñƒ
      - name: ğŸ—ï¸ Build Backend
        run: |
          cd book-store-backend
          npm install
          npm run build

  commit-lint:
    name: ğŸ“ Commit Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install Commitlint
        run: npm install --save-dev @commitlint/config-conventional @commitlint/cli
      - name: Validate current commit
        if: github.event_name == 'push'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose
      - name: Validate PR commits
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
